# https://docs.travis-ci.com/user/languages/python/
language: python

# https://docs.travis-ci.com/user/caching/#pip-cache
cache: pip

# https://docs.travis-ci.com/user/docker/
services:
- docker

python:
- '3.6'

sudo: required

before_install:
- docker info
- sudo apt update
- sudo apt install -y swig # FIXME: can't install libopencv-dev on travis CI
- pip install -r requirements.txt
- pip install pycocotools  # must be installed after cython is installed
- ./scripts/install-pafprocess.sh
- ./scripts/download-test-data.sh

script:
- docker build --rm -t openpose-plus-test:snapshot -f docker/Dockerfile.travis-ci .
- docker run --rm -it openpose-plus-test:snapshot sh -c './configure --build-fake --with-trace && make && make test'
- python ./examples/example-inference-1.py --path-to-npz='' --images=$(ls data/media/*.jpg | sort | head -n 3 | tr '\n' ',') --base-model=vgg
- python ./examples/example-inference-1.py --path-to-npz='' --images=$(ls data/media/*.jpg | sort | head -n 3 | tr '\n' ',') --base-model=vggtiny
- python ./examples/example-inference-1.py --path-to-npz='' --images=$(ls data/media/*.jpg | sort | head -n 3 | tr '\n' ',') --base-model=mobilenet

- wget https://media.githubusercontent.com/media/tensorlayer/pretrained-models/master/models/openpose-plus/hao28-pose345000.npz
- python ./examples/example-inference-1.py --path-to-npz='hao28-pose345000.npz' --images=$(ls data/media/*.jpg | sort | head -n 3 | tr '\n' ',') --base-model=hao28_experimental
