# https://docs.travis-ci.com/user/languages/python/
language: python

python:
  - '3.6'
  - '2.7'

sudo: required

before_install:
- sudo apt install -y swig
- pip install -r requirements.txt
- pip install pycocotools  # must be installed after cython is installed
- pip install git+https://github.com/tensorlayer/tensorlayer.git  # TODO: create a latest release for TL
- ./scripts/install-pafprocess.sh
- ./scripts/download-test-data.sh

script:
- make
- python ./test_inference.py --path-to-npz='' --images=$(ls data/media/*.jpg | sort | head -n 3 | tr '\n' ',') --base-model=vgg
- python ./test_inference.py --path-to-npz='' --images=$(ls data/media/*.jpg | sort | head -n 3 | tr '\n' ',') --base-model=vggtiny
- python ./test_inference.py --path-to-npz='' --images=$(ls data/media/*.jpg | sort | head -n 3 | tr '\n' ',') --base-model=mobilenet
# TODO: add move tests
