# https://docs.travis-ci.com/user/languages/cpp/
language: cpp

sudo: required

before_install:
- sudo apt install -y swig

script:
# The default is
# - ./configure && make && make test
- cd inference/pafprocess && make
# TODO: add move tests
