name: CI

on: [push]

jobs:
  build:

    # https://help.github.com/en/articles/virtual-environments-for-github-actions#supported-virtual-environments
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - run: apt-get install libopencv-dev # dependency
    - run: sh scripts/download-test-data.sh
    - run: sh scripts/download-tinyvgg-model.sh
    - run: sh scripts/download-openpose-thin-model.sh
    - run: sh scripts/download-openpose-res50-model.sh
    - run: sh scripts/download-openpose-coco-model.sh
    - run: cmake . -DBUILD_TESTS=1 -DBUILD_LIB=0 -DBUILD_EXAMPLES=0 -DBUILD_USER_CODES=0 -DEXECUTABLE_OUTPUT_PATH=./bin
    - run: cmake --build . --config Release

    # - run: ctest -C Release
    # - run: ./bin/test.thread_pool
    # - run: ./bin/test.thread_safe_queue
